### ISSUE TITLE
Quick draft example of NICHE `zuur` and `trofie` using numpy

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/niche_vlaanderen#1]
@johanvdw you can find a quick/draft exploration of the `trofie` and `zuur` modules at: https://gist.github.com/stijnvanhoey/127ef731b7e51bac6506eec695b58910

I made this to illustrate some Python concepts (numpy working on arrays, using functions, self-written classify,...) in the scope of a course, so don't feel yourself restricted to the choice of `numpy` in the further implementation. However, I would keep the idea of having re-usable functions (classification) in the package development.

**Comment by johanvdw** [comment]
Thanks - I think using numpy is a no-brainer here. For classification, we can probably rely on numpy.digitize.

**Comment by stijnvanhoey** [comment]
I agree. The `digitize` functions seems appropriate, cool (always nice to learn new numpy functions)!
Hence, the internal calculations of NICHE would depend on a set of completely similar matrices/arrays (no specific GIS component required). The connection with the GIS-formats can be done on the pre- and postprocessing level.

**Comment by johanvdw** [comment]
@stijnvanhoey ,

As this still relies on the old complex classification tables, I will have to use a different approach. But during testing I updated some things which you may find interesting. Eg the no-data handling:

https://gist.github.com/johanvdw/b119b907f74bc25dc0df029b842d15de

**Comment by stijnvanhoey** [comment]
If I understand correctly, the `numpy` functionality will remain, but the effective implementation altered? No problem, the original code in the gist was a quick test-case. The handling of no-data as zero-values is - certainly in a reclassification context -  rather strange. However, the reasoning is probably the lack of a proper Nan-handling for the `numpy` `integer` data type. Whereas `float` arrays can have Nan-values, this is not fully supported for `integer` arrays. What would you propose to tackle this?

**Comment by johanvdw** [comment]
Actually the 0 value was in the original code as well. I prefer using sth like -99 if it is not possible to use NA.

Anyway, I am not sure we will still be able to use efficient an numpy implementation once we have to combine a selection using one class variable (eg soil class) and one numeric variable as in eg
https://inbo.github.io/niche-vlaanderen/trofie.html#stikstofmineralisatie

**Comment by johanvdw** [comment]
Note that yesterday I tried some methods to use both categorical and continuous variables at the same time.

I think the best method is using a two step approach where we loop over the categorical variables and use digitize to classify the continuous variables.

https://gist.github.com/johanvdw/0a2be36a8d34222285a9ae55a0e3b1ad

**Comment by peterdesmet** [comment]
For categorical variables (which are currently expressed as integers) I'd only use -99 if it is kept internal (not in input or output).

**Comment by stijnvanhoey** [comment]
Another option would be to handle all categorical values (represented either as numbers or characters) as strings, which handles Nan-values as 'nan' strings:
```
In [4]: np.array(['1', '2', np.nan])
Out[4]: 
array(['1', '2', 'nan'], dtype='<U3')
```
I personlly like the `'nan'` string representation more than a picked vale of `-99`. However, I currently can't say if this would cause a performance compared to integer dtype handling?

Stijn

**Comment by johanvdw** [comment]
Categorical variables like soiltype coming from a grid will be integer
values. Note that they will/should have a nodata value assigned inside
which we can read from the grid file with gdal.

 ds.GetRasterBand(1).GetNoDataValue()


Our exported grids will set one value as no data as well. As the export
actually contains 0 or 1 as values (vegetation present/absent) we
definitely don't want to use 0 there for nodata. As our grids will have 1
byte, we can probably use -127 (if signed) or 255 (if unsigned).
The second option is currently used:
https://raw.githubusercontent.com/inbo/niche_vlaanderen/master/testcase/VegNoEffectsRef/v12.asc


Any reasonable GIS package will read the nodata field anyway so the user
should not see the difference.

Kind Regards,
Johan

**Comment by johanvdw** [comment]
Numpy has masked arrays, which are also supported by rasterio. I am considering using those.
