### ISSUE TITLE
Testing niche on MacOSX

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#100]
Good news, this issue is not an issue, I just want to gather some information on my attempts to install and test niche on my own computer that happens to be an old Mac running an old OS. 

Maybe this could be mentioned in the documentation or FAQ as "this installation procedure has been reported to work on xxx", or "niche has been reported to run on xxx", meaning not intensively tested, but at least no major issues at first sight.

**Comment by cecileherr** [comment]
Here we go:

* niche_vlaanderen version: 1.0b1
* Python version: 3.6
* Operating System: MacOS X 10.9.5

## Niche Python Package question

I was able to install miniconda with python 3.6, jupyter notebook and niche 1.0b1 without too much hassle following the instructions in the alternative installation section.
Good to know: 
Rasterstats was not directly available in conda ("following packages are not available from current channels"), I had to install it via pip
`/Users/cecileherr/miniconda3/bin/pip install rasterstats`

I am able to run a simple niche model and I get the same error as in Win for the full model  ( #99 ), not a bad start!

**Comment by johanvdw** [comment]
Note I updated the installation instructions in  16d449ddbcc0ed4f6b5f882ae6385ca93214c7dc 

Keeping this open as I'm interested in hearing further results from OSX

**Comment by cecileherr** [comment]
I will update my OS soon (to 10.11), let me know if you want me to test something specific on the old 10.5 before that. 
I will anyway go on with testing on 10.11 (unfortunately this is the most recent OS I will ever be able to install on my old 2009 mac)

**Comment by johanvdw** [comment]
I don't think we should
