### ISSUE TITLE
Config file: using your own niche_vegetation table

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#106]
* niche_vlaanderen version:1.0b2
* Python version:3.6
* Operating System:win

## Niche Python Package question

The config file mentions:
> optionally code tables can be overwritten
> code_tables:
> ct_soil_code: newsoilcode.csv

Could you maybe replace that example by an example for a custom niche_vegetation.csv table? This will be the most usual case. 

Is this option already active? I tried several variations on this code, unsuccessfully:

```
code_tables:
    ct_vegetation: nicheveg12.csv
```

**Comment by johanvdw** [comment]
If you don't use the command line interface: make sure you use the overwrite_ct parameter.

This is actually one where we could switch the default value - there is something to say for both options.

https://inbo.github.io/niche_vlaanderen/lowlevel.html#niche_vlaanderen.Niche.read_config_file

**Comment by cecileherr** [comment]
OK, thanks, got it!

I have no preference for the default. I will ask the colleagues whether they think this should stay an advanced option (then it could stay false as default) or make this easily available (in the latter case we could also add an example in the tutorials).

I have a practical problem trying to use my custom niche_vegetation table: since the custom table does not include all the existing combinations for nutrient_level, acidity and management anymore, I get "inner_join" errors like :

> CodeTableException                        Traceback (most recent call last)
> <ipython-input-10-17cf34293014> in <module>()
>       2 # a simple model - we start directly from here with a config file
>       3 simple = nv.Niche()
> ----> 4 simple.run_config_file("ConfigSimpleM12.yml",overwrite_ct=True) #run=also wite with overwrite = false
> 
> ~\AppData\Local\Continuum\anaconda3\envs\niche\lib\site-packages\niche_vlaanderen\niche.py in run_config_file(self, config, overwrite_ct)
>     274             full_model = False
>     275 
> --> 276         self.run(full_model, deviation)
>     277 
>     278         if "floodplains" in self._options:
> 
> ~\AppData\Local\Continuum\anaconda3\envs\niche\lib\site-packages\niche_vlaanderen\niche.py in run(self, full_model, deviation, abiotic, strict_checks)
>     513             ct_veg[k] = self._code_tables[k]
>     514 
> --> 515         vegetation = Vegetation(**ct_veg)
>     516         if "inundation_vegetation" not in self._inputarray:
>     517             self._inputarray["inundation_vegetation"] = None
> 
> ~\AppData\Local\Continuum\anaconda3\envs\niche\lib\site-packages\niche_vlaanderen\vegetation.py in __init__(self, ct_vegetation, ct_soil_code, ct_acidity, ct_management, ct_nutrient_level, ct_inundation)
>      80                                    ct_management=self._ct_management,
>      81                                    ct_nutrient_level=self._ct_nutrient_level,
> ---> 82                                    ct_inundation=self._ct_inundation)
>      83 
>      84         # join soil_code to soil_name where needed
> 
> ~\AppData\Local\Continuum\anaconda3\envs\niche\lib\site-packages\niche_vlaanderen\codetables.py in validate_tables_vegetation(ct_vegetation, ct_soil_code, ct_inundation, ct_management, ct_acidity, ct_nutrient_level)
>     118 
>     119     check_inner_join(ct_vegetation, ct_inundation, "inundation")
> --> 120     check_inner_join(ct_vegetation, ct_acidity, "acidity")
>     121     check_inner_join(ct_vegetation, ct_nutrient_level, "nutrient_level",
>     122                      "code")
> 
> ~\AppData\Local\Continuum\anaconda3\envs\niche\lib\site-packages\niche_vlaanderen\codetables.py in check_inner_join(df1, df2, f1, f2)
>      60         print(u2)
>      61         raise CodeTableException(
> ---> 62             "Different keys exist in tables.")
>      63 
>      64 
> 
> CodeTableException: Different keys exist in tables.

Any idea of a workaround?

**Comment by johanvdw** [comment]
If you just want a workaround to check if codetables are overwritten, you can remove an entire vegetation type.

eg
https://github.com/inbo/niche_vlaanderen/blob/master/tests/data/bad_ct/one_vegetation.csv
is used in the tests.

Otherwise you will have to change different codetables. This is on purpose: If the codetables are not internally consistent you should get a "codetableexception".

**Comment by cecileherr** [comment]
> Otherwise you will have to change different codetables. This is on purpose: If the codetables are not internally consistent you should get a "codetableexception".

This sounds like it will be quite complicated to use another vegetation table, no? Actually we quite often use modified versions of the table, or reduced versions with only a few vegetations of interest instead of the whole list (eg in some parts of Flanders with very acid soils, I do not calculate predictions for the calcareous grasslands and alkaline fens ...)
Maybe it is not an option for a basic user, but it is quite usual for us.

I would really prefer not to have to modify (manually?) the other basis tables acidity.csv, management.csv, ... 
Does the consistency between tables really have to be in both directions? All categories in niche_vegetation should be in respectively acidity.csv, management.csv, ... but maybe is the contrary not essential ??? (sorry for the very naive question :-))

**Comment by johanvdw** [comment]
I had a few thoughts on this:
* validation in one direction always has to happen: eg you can not use an acidity type in the vegetation table that is not present in the acidity table
* two way validation should be done for the codetables in the package itself - if these are not complete that seems an error
* If you override tables, perhaps one way validation is enough, but I think we should add a warning mentioning which types are not covered.

**Comment by cecileherr** [comment]
> If you override tables, perhaps one way validation is enough, but I think we should add a warning mentioning which types are not covered.

This sounds good to me!

**Comment by cecileherr** [comment]
OK, thank you, it works smoothly in 1.0b3!

The warning is not that clear, and could be improved by adding the variable name, but this is a detail.

> [1 2]
> [1 2 3]
> [1 2 3]
> [1 2 3 4 5]
> [0 1]
> [0 1 2 3]

> C:\Users\cecile_herr\AppData\Local\Continuum\anaconda3\envs\niche\lib\site-packages\niche_vlaanderen\codetables.py:72: UserWarning: Warning, different keys exist in tables
>   warnings.warn("Warning, different keys exist in tables")
