### ISSUE TITLE
Dutch labels in the floodplains module

### ISSUE THREAD

**Issue by milotictanja** [inbo/niche_vlaanderen#107]
* niche_vlaanderen version:1.0b1
* Python version:3.6
* Operating System:Windows7

### Description

I ran the floodplain module using Jupyter notebook. In the summary table, there are some Dutch labels in the 'presence' column. This is also the case for the plots generated with the floodplains module. As the labels of all other output seem to be in English, this is a bit inconsistent.

**Comment by johanvdw** [comment]
See : https://github.com/inbo/niche_vlaanderen/pull/108
