### ISSUE TITLE
Simple niche runreturns not present instead of nodata

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#110]
* niche_vlaanderen version: 1.0b3
* Python version: 3.6
* Operating System: win

## Niche Python Package question

I tried to run a simple niche model for the test case Grobbendonk and I get a result (not present) in areas with nodata values in one of my input layers. These areas should be set to nodata. 

See attachment:
![nodata_vs_nopot](https://user-images.githubusercontent.com/31855012/37144684-139f5d9c-22bf-11e8-9334-b4f1283227e8.PNG)

**Comment by cecileherr** [comment]
And same problem if I try to compute the deviations in the groundwater levels:
![dev_nodata](https://user-images.githubusercontent.com/31855012/37146862-4c032a6e-22c5-11e8-83dc-f247e7c43d72.PNG)

**Comment by cecileherr** [comment]
And also if I use abiotic = True:
![abiotictrue](https://user-images.githubusercontent.com/31855012/37147235-87919b28-22c6-11e8-852a-3e4ddcda7e64.PNG)

**Comment by johanvdw** [comment]
Issue was closed in 1.0b5
