### ISSUE TITLE
Language choice of tutorial

### ISSUE THREAD

**Issue by damianooldoni** [inbo/niche_vlaanderen#112]
* niche_vlaanderen version: 1.0a10
* Python version: 3.6.4
* Operating System: Windows 7 Professional Service Pack 1

## Niche tutorial
Do you have plans to translate the model description in English? Or to translate the second part about package in Dutch?

### Description
The package is very well documented ([https://inbo.github.io/niche_vlaanderen/]()). Congrats! The model description (*model beschrijving*) is in Dutch. I know that the model has been originally developed from a Dutch research centre and the users are mainly Dutch speaking researchers who read easily English tests as well. However, it would be better to have a complete bilingual tutorial. Or as easier alternative: translating the *model beschrijving* section in English.

**Comment by stijnvanhoey** [comment]
Valid comment, but we decided, with the researchers, to keep the original language for the moment directly converted from the dutch report, while having the new technical elements (the new implementation) in english.
