### ISSUE TITLE
Warning: "Passing list-likes to .loc or [] with any missing label"

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#115]
* niche_vlaanderen version: 1.0b5
* Python version:3
* Operating System:win

## Niche Python Package question

I get a warning when I run a full niche model (with Grobbendonk test data)
(I think this warning was already present in older versions, but the project is now ripe enough to start tackling the cosmetic issues :-) )

> C:\Users\cecile_herr\AppData\Local\Continuum\anaconda3\envs\niche\lib\site-packages\pandas\core\series.py:696: FutureWarning: 
> Passing list-likes to .loc or [] with any missing label will raise
> KeyError in the future, you can use .reindex() as an alternative.
> See the documentation here:
> http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
>   return self.loc[key]

**Comment by johanvdw** [comment]
Closed in 5dfc80278203d2f
