### ISSUE TITLE
Documentation Niche Configuration file>Full example

### ISSUE THREAD

**Issue by DriesAdriaens** [inbo/niche_vlaanderen#118]
* niche_vlaanderen version: 1.05b
* Python version: 3.6.4
* Operating System: Windows

## Documentation

Is it possible to mention the floodplains block, as described higher, explicitely in the full example configuration file? And as such also in the text that is generated by the command line ``niche --example``?

**Comment by johanvdw** [comment]
Closed in 0dd7d444f2ec4175b80a67466980a98d91c6e3d6
