### ISSUE TITLE
Enable overwrite_files for niche_vlaanderen.Floodplain.combine.write

### ISSUE THREAD

**Issue by DriesAdriaens** [inbo/niche_vlaanderen#120]
* niche_vlaanderen version: 1.0b5
* Python version: 3.6.4
* Operating System: Windows

### Description

Would it be possible to enable the parameter ``overwrite_files`` for ``niche_vlaanderen.Floodplain.combine.write?

### What I Did

![image](https://user-images.githubusercontent.com/31617046/38079225-aab31e82-333e-11e8-8c29-150155b85135.png)

**Comment by johanvdw** [comment]
Duplicates (#119 ) (a combined model is a special case of a normal Floodplain model)
