### ISSUE TITLE
Model_option abiotic = True not interpreted by run_config_file()

### ISSUE THREAD

**Issue by DriesAdriaens** [inbo/niche_vlaanderen#123]
* niche_vlaanderen version: 1.0b5
* Python version: 3.6.4
* Operating System: Windows

### Description

I tried to rerun a Niche model from the log file generated in the output directory. It was a model with forced abiotic grids. This is correctly mentioned in the log file (abiotic: true under model_options; see attached log file) but nonetheless I receive a warning that the abiotic inputs are specified but that these will not be used because it is not specified in the model options. The model output that is written is ignoring the abiotic grids indeed. What did I do wrong?

### What I Did
![image](https://user-images.githubusercontent.com/31617046/38133993-aa8cf0ee-3411-11e8-9aa5-2454a4f91ce8.png)
![image](https://user-images.githubusercontent.com/31617046/38134115-005ca794-3412-11e8-85d1-3b901b730484.png)

[Dyl50_log.txt](https://github.com/inbo/niche_vlaanderen/files/1863318/Dyl50_log.txt)

**Comment by johanvdw** [comment]
Closed in  https://github.com/inbo/niche_vlaanderen/commit/b5e0d1d99ae9326e71d047f841c638bfbb41e56b and https://github.com/inbo/niche_vlaanderen/commit/e14195fa8b05dd8d689a5c06db559ed68ebf2684
