### ISSUE TITLE
Creating statistics per shape object (zonal_stats):  use alternative meaningful field to shape_id

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#131]
* niche_vlaanderen version: 1.0b6
* Python version: 3.x
* Operating System: Win

## Niche Python Package question

A suggestion for enhancement after testing the model with a new user

The zonal stats function gives the surface area for each shape_id. It would be much easier for the end user to be able to choose a more meaningful field in his shapefile and to get the surface area expressed in terms of this meaningful field. 

=> suggestion for improvement: add an option in the zonal_stats to let the user select a field from the shapefile used (shape_id could be the default if no field name is provided by the user)

**Comment by stijnvanhoey** [comment]
just related small issue on the documentation in the same function: the [actual](https://github.com/inbo/niche_vlaanderen/blob/9a18576948ad73a3b7cbcc1aa945a1fe8a2103b7/niche_vlaanderen/niche.py#L781) default and the [documented default ](https://github.com/inbo/niche_vlaanderen/blob/9a18576948ad73a3b7cbcc1aa945a1fe8a2103b7/niche_vlaanderen/niche.py#L792)for `outside` are not the same

**Comment by johanvdw** [comment]
Should be tested combined with the outside option as well.
