### ISSUE TITLE
High level API design

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#14]
Goal of this issue is to define the High level API of the niche_vlaanderen module.

# Low level API

The low level API is now more or less finished. Basically this low level api consists of 3 functions which calculate the possible vegetation based on input numpy _arrays_.
These three functions are each wrapped in a class which will load (and validate) the classification tables, which can be overwritten on model initialization.

The three classes are:
* [Vegetation](https://github.com/inbo/niche_vlaanderen/blob/master/niche_vlaanderen/vegetation.py)
* [Acidity](https://github.com/inbo/niche_vlaanderen/blob/master/niche_vlaanderen/acidity.py)
* [NutrientLevel](https://github.com/inbo/niche_vlaanderen/blob/master/niche_vlaanderen/nutrient_level.py)

# High level API
For the high level API, the proposed method is:
A `Niche` object. This is normally initialized with its own codetables, but optionally different codetables can be given. The model is fixed when the object is created.

## Initialization

```
import niche_vlaanderen
my_niche = niche_vlaanderen.Niche()
```
Internally, this object contains a (private)dictionary with reference to the different input layers
`
my_niche._input_layers
`
The keys of this dictionary are a limited number of allowed strings:

- soil_code
- mhw
- mlw
- seepage, ...

My first idea here was working with an [enum type](https://github.com/inbo/niche_vlaanderen/blob/4bea816f8cef7460682a2cce4756d9b5869705ef/niche_vlaanderen/input_types.py) but I think this adds some complexity for the user with little benefit (eg you have to import the types to use them, enum is not supported natively on python 2.7).

## Adding input data

After creating the module, the user can add different layers to this dictionary. A method is provided for this which does some basic sanity checking (valid type, valid file, ...). 

`myniche.set_input("msw", "gvg-zelfberekend.tif")`

One of the choices here is how we handle the spatial constraints (projection, grid system, ...).
We could implicitly derive them from the first grid, define them explicitly or require the user to explicitly define them by importing a file.

1. Implicitely setting the context
 ```
>>> my_niche = niche_vlaanderen.Niche()
>>> myniche.set_input("msw", "gvg-zelfberekend.tif")
>>> myniche.set_input("soil_code", "../otherarea/soil.tif")
Error: layer extent does not overlap
```

2. Explicitly setting the context
```
>>> my_niche = niche_vlaanderen.Niche()
>>> my_niche_define_spatial_context(projection="EPSG:31370", bbox= ..., cell_size = 20)
```
3. Explicitely setting the context
```
>>> my_niche = niche_vlaanderen.Niche()
>>> myniche.set_input("msw", "gvg-zelfberekend.tif")
 Error: no spatial extent has been set
>>> myniche.set_input("msw", "gvg-zelfberekend.tif", set_spatial_extent=True)
 Spatial extent has been set: projection= ... , bbox ....
```

A second question is whether we should support different grid systems (overlapping). This is currently the case. Eg the Grobbendonk testcase has such grids.

### Set constant input
A constant value can also be used as input:
```
>>> my_niche = niche_vlaanderen.Niche()
>>> my_niche.set_constant_input("nitrogen_atmospheric", 30)
```

## Running the Model

The actual calculation can then be started with a `calculate` method.
`myniche.calculate()`
This will validate that all required input layers are set. Il will convert the `self._input_layers` to a `self._input_arrays` dictionary which contains arrays with the actual data that will be passed to the low level api.

It should output useful messages if errors occur.
```
>>> myniche.calculate()
Error, no value have been set for rainwater
```
If no errors occur, a list of vegetation types that were found should be reported. This gives the user some feedback (eg if impossible vegetations are found here the input should be checked) without having to open the grid files.
```
>>> myniche.calculate()
Vegetation types that can occur:
7: Caricion gracilis
...
```

A slightly more complicated output may actually present what percentage of the area can be covered by a certain vegetation type.
7: Caricion gracilis - 6%

## Saving the model results

The result of this method will be saved in the class itself (eg `self._vegetation`). It can be saved to GIS files using the `write()` method:

> `myniche.write("../vegetation")`

Files written have a fixed name (V1.tif, V2.tif, ...) and data type (geotiff). Optionally a different datatype (codelist from [GDAL](http://www.gdal.org/formats_list.html)) can be specified eg ascii raster (useful for human readable test output).

> `myniche.write("vegetation", datatype="AAIGrid")`

The intermediate "abiotic" grids will be saved in the same directory as well.

**Comment by stijnvanhoey** [comment]
I like the proposed structure.

Just a small idea/enhancement: you could provide the methods to provide basic sanity checking (valid type, valid file, ...) as decorator functions on top of the `set_input` and `set_constant_input` functions. This makes the checks very explicit and in case other `set_input` derivative functions appear, it is not cluttering the insides of the functions/methods, but usage of the decorators

**Comment by johanvdw** [comment]
This has been implemented. Further documentation will happen in the dev documentation(#36)
