### ISSUE TITLE
Generate errors on invalid values

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#16]
eg Nitrogen: <0 or >10000

**Comment by johanvdw** [comment]
Tests are in place now
d63bc46803aabdb1fae0864922f6c0a15971430a

**Comment by cecileherr** [comment]
Regarding the tests for the groundwater levels:
I recently had the case  inputarray.mlw = inputarray.msw +1 cm for 3 pixels out of more than 80000, quite clearly a rounding error
Would it be an option to allow a tolerance of 1 cm ? Or should we be strict on that sort of issues ?

**Comment by cecileherr** [comment]
I tested some other datasets and it appears that the validation for the groundwater levels generates errors ... in most of the cases! We think we should be less strict on this issue, for example generate a warning instead of an error. Could you implement this (or do you have any objections against warnings)?

**Comment by johanvdw** [comment]
I can definitely change this - I'll make it a warning.
https://github.com/inbo/niche_vlaanderen/blob/master/niche_vlaanderen/niche.py#L262

**Comment by johanvdw** [comment]
Reopened because of comment of cecile above.

**Comment by johanvdw** [comment]
I added an option "strict_checks" to the configuration file or the module options so this check can be disabled.
The recommended usage would be to leave this to true by default, and change it when you have verified that the problems reported can be neglected.

This should probably also apply to coordinate system checks, as I have seen that there may be false warnings (eg when standard parallels are flipped, which is mathematically the same).

**Comment by johanvdw** [comment]
Fixed using the strict_checks parameter.
