### ISSUE TITLE
Flooding module via configuration file: (also) show "combined" results

### ISSUE THREAD

**Issue by DriesAdriaens** [inbo/niche_vlaanderen#190]
* niche_vlaanderen version: 1.0b7
* Python version: 3.6.4
* Operating System: Win 7 SP1

### Description
When using the flooding module via the configuration file, the resulting rasters show the theoretical flooding tolerance for each vegetation type without notice about where NICHE Vlaanderen actually predicts the type. It would be more useful if the results of the **combination** of NICHE Vlaanderen (potential) and the flooding tolerance is shown (i.e. result of the `niche_vlaanderen.Flooding.combine`, with the extra class "not present (niche)" (-1)). 

#### Raster file naming
The rasters with the theoretical flooding tolerance could be retained, besides the "combined" rasters. However, clear distinction should be made between both raster types by appropriate file naming. Suggestion: add "-comb-niche" as suffix for the "combined" rasters.

#### Summary files
The summary file(s) (csv) for the "combined" rasters of (a) particular scenario(s) should be added as well. Here, too, adding the "-comb-niche" suffix should be considered.

### What I Did

```
test = nv.Niche()
test.run_config_file("Dyl50_log.txt")
```
[Dyl50_log.txt](https://github.com/inbo/niche_vlaanderen/files/2031264/Dyl50_log.txt)

**Comment by johanvdw** [comment]
@DriesAdriaens: this is actually a bug, I intended to save only the combined results.
Would it be sufficient to return only the combined rasters and csv? I think this is less complicated for the user, but if it would be useful to save both I can do that as well.

**Comment by DriesAdriaens** [comment]
@johanvdw Only providing the combined rasters would be fine. Less complicated for interpreting correctly indeed.
