### ISSUE TITLE
test compatibility with pandas 0.23

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#196]
Pandas 0.23 was released recently. As we heavily rely on this library we should check if everything still works as expected when using this version.

**Comment by stijnvanhoey** [comment]
On option is to include the [pyup ](https://pyup.io/)service for our dependencies, which will initiate a PR and the tests when new versions are available.

**Comment by johanvdw** [comment]
Good idea, it is running right now: https://github.com/inbo/niche_vlaanderen/pull/197
