### ISSUE TITLE
Opsplitsen kolommen codetabellen

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#2]
De codetabellen zijn momenteel steeds gebaseerd op twee kolommen, waarbij een berekende waarde omgezet wordt naar een gecodeerde waarde.

In een aantal gevallen maakt dit de logica onnodig complex. Ik stel dan ook voor om deze op te splitsen en een kolom te voorzien per variabele.

Een voorbeeld:
In de tabel BgvgTrofie gebeurt de omzetting van een bodemtype (klassevariabele) en een GVG (numerieke waarde).
Vroeger stond hier: bvb
35000 40005 : 18
Nu wordt dit

bodemcijfercode|gvg_min|gvg_max|N_mineralisatie|old_min|old_max|
---|---|---|---|---|---|
40000|-5000| 5|18| 35000| 40005

Hierdoor zijn de codetabellen veel gemakkelijker te interpreteren en te onderhouden, en het maakt de logica veel doorzichtiger. De kolommen old_min en old_max zullen niet verder gebruikt worden, maar geven de oude waarde waaruit de andere kolommen afgeleid werden.

De waarden voor bodemcijfercode werden overigens ook al toegevoegd in een nieuwe codetabel.

**Comment by stijnvanhoey** [comment]
Good point, human-readable/understandable categories seems more appropriate ;-)

**Comment by johanvdw** [comment]
@stijnvanhoey , @peterdesmet 
I'm wondering what I should do with the column titles in the csv. Keep them all lower case (as I would do for database tables), or camel case or sth else?

Currently we have a mess (about everything).

**Comment by peterdesmet** [comment]
I'd opt for `lower_underscore`

**Comment by johanvdw** [comment]
All codetables have been renamed
