### ISSUE TITLE
Update github but not website?

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#201]
* Python version: 3
* Operating System: Win 7

## Niche Python Package question

Last week I added a figure on github (documentation trofie.rst), and I can see it in the master on github, but not in the website. Any idea what the problem could be?

Compare:
https://inbo.github.io/niche_vlaanderen/trofie.html
https://github.com/INBO/niche_vlaanderen/blob/master/docs/trofie.rst

Thanks in advance!

**Comment by stijnvanhoey** [comment]
@johanvdw the build error is probably due to the fact that version of pip no longer supports the `--use-wheel` option, see https://github.com/saltstack/salt/issues/46803 

Any specific reason for this option?

**Comment by stijnvanhoey** [comment]
@cecileherr should be ok now. Can you have a look and close this issue if all ok?
