### ISSUE TITLE
Working with rasters with asymmetrical (rectangular) cells?

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#204]
* niche_vlaanderen version: 1.0
* Python version: 3
* Operating System: Win 7

## Niche Python Package question

Can the model be used with input rasters with asymmetrical cells? (not square, but rectangular ones). I do not have the needed input files (yet) to test it by myself (but if nobody knows the answer I'll make them and give it a try)
Thanks in advance!

**Comment by johanvdw** [comment]
I have not tested this, but I'm quite sure that this should not be an issue. All grids do have to use the same system though, we don't reproject.

**Comment by cecileherr** [comment]
OK, thanks! I will try it, report the result here and close the issue when it is done

**Comment by cecileherr** [comment]
No extensive testing yet, but the first tests were succesful, so I close the issue

**Comment by johanvdw** [comment]
I think we should consider creating a 1.0.1 release so users will install
these fixes by default.

**Comment by stijnvanhoey** [comment]
which _fixes_? As this just seem to work without adjustments?

**Comment by johanvdw** [comment]
@stijnvanhoey : this fix: https://github.com/inbo/niche_vlaanderen/commit/c64d8659d0ef69594a545c1e906cdf5a9c9e9097

cecile is using master and not a released version.

Apart from that some smaller issues have been dealt with, mostly warnings from packages we depend on.

**Comment by stijnvanhoey** [comment]
Thanks for clarifying. I agree, bump new release would be good!

**Comment by cecileherr** [comment]
Yes, we will have a new official NICHE project soon that would require the corrected version. It would be nice to be able to use an official version.

**Comment by cecileherr** [comment]
> But please note there might be a small bug (abiotic tiffs not always exported) that I want to check today or tomorrow, so maybe beter to wait until we know if there is another small correction needed?

I checked and good news: I found no bug, so OK for a new release with the fixes for the small shift in spatial overlap
