### ISSUE TITLE
Compare different model results

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#22]
Liefst in shapefile.

**Comment by johanvdw** [comment]
opsplitsen (2 aparte issues)

**Comment by johanvdw** [comment]
Issue split (#37) - this issue is only the model result comparison

**Comment by johanvdw** [comment]
Cfr combine in arcgis:
http://pro.arcgis.com/en/pro-app/tool-reference/spatial-analyst/combine.htm

**Comment by stijnvanhoey** [comment]
Furthermore, it needs to be checked how we handle the no data in the combinations, which could result in a 5/6 option besides the 4 combinations provided by the `combine` function.
