### ISSUE TITLE
Should we support python 2 any longer

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/niche_vlaanderen#222]
The shift towards Python 3 is now becoming most general and more and more packages are no longer supporting Python 2. For example, if we want to align with the latest versions of Matplotlib, Python 2 is not an option anymore.

We have different options:
- Fix the versions of all dependencies, provide that as install environment and stop further adjustment to make sure the code is following newer versions.
- Actively maintain support for Python 2 by adjusting our test-suite and CI and no longer use pyup again
- Drop Python 2 and keep niche in alignment to the developments of numpy/matplotlib/... by providing the required patches when needed.

**Comment by johanvdw** [comment]
As mentioned in the release notes, version 1.1. is the last version supporting Python 2. For future development, we can ignore Python2.
