### ISSUE TITLE
Generate deviation between the range (mhw/mlw) and the actual value per type

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#23]
Based on the vegetation table, create grids with how much the mhw (or mlw) needs to change to allow a certain vegetation type.
Example map below:
![afw_r1_v27_ghg](https://user-images.githubusercontent.com/868434/31130544-fda359b2-a857-11e7-85d5-d700d01390fb.png)

These maps don't take into account nutrient level and acidity

**Comment by johanvdw** [comment]
This is based on the simple NICHE model, not taking into account nutrient level and acidity.

**Comment by stijnvanhoey** [comment]
Currently, the deviation plots are empty...

**Comment by johanvdw** [comment]
The plots are actually ok when checked in qgis or saga. I opened using a picture application, which was not a good idea.

**Comment by stijnvanhoey** [comment]
We discussed the handling of the legend again. The basic functionality has an argument `fixed_scale=TRUE` as argument, which results in a range `[-100, 100]` (cfr. supra). 

If user decides to use: `fixed_scale=FALSE`, the data range is just translated to the scale.
