### ISSUE TITLE
Abiotic: use custom acidity OR nutrient_level

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#259]
* niche_vlaanderen version: 1.0
* Python version: 3
* Operating System: Win 

### Description
If you use  mymodel.run( abiotic= True), you need to provide both an input layer for acidity and nutrient_level. 

It happens regularly that we need only one custom layer (in my case: most often a custom layer for acidity while I use the standard nutrient_level), so I have to run the model twice (first run to produce the nutrient_level, and another with the custom acidity and standard nutrient_level) . 
It would be very nice to be able to use only a custom acidity or only a custom nutrient_level without having to run the model twice.

**Comment by cecileherr** [comment]
Please also note that the abiotic layer which is not provided by the user should be exported with the write commando (eg. if the user provides a custom acidity layer, the calculated nutrient_level.tif should be exported). Presently the write commando does not export any abiotic layers if the model runs with "abiotic= True"

**Comment by johanvdw** [comment]
Perhaps we can adjust the logic:
if `acidity` or `nutrient_level` is defined as an input, don't calculate it again.

In that case, I think we can also remove the `abiotic` option (we can leave it for compatibility reasons).

In that case you could eg do: 
```
adjusted = nv.Niche()
adjusted.read_config_file("full.yml")
adjusted.set_input("acidity", "output_abiotic/full_acidity.tif")
adjusted.name = "adjusted"
adjusted.run()

adjusted.plot(7)
full.plot(7)
plt.show()
```

**Comment by johanvdw** [comment]
TODO: check that acidity is exported when using write if only nutrient_level is defined and vice versa.
