### ISSUE TITLE
Error when trying to install niche on Win 10

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#260]
* niche_vlaanderen version: (none yet)
* Python version: 3.7
* Operating System: Win 10

## Niche Python Package question

The present problem might be related to this issue https://github.com/inbo/niche_vlaanderen/issues/203

### Description

We tried to install niche on Wim's new computer (@WimMertens), in vain

![Error](https://user-images.githubusercontent.com/31855012/60269293-755a4780-98ee-11e9-8940-dd6600437cdc.png)

Is this still a conda problem? Is there any workaround?
Many thanks in advance

**Comment by johanvdw** [comment]
@WimMertens, @cecileherr : can you verify the following instructions work. If these work, they should probably replace the old method.
```
conda create --name niche

# Should this give an error because the niche environment already exists you can remove it
# using this command: conda env remove --name niche

# activate the new environment
activate niche

# install binary dependencies
conda install pandas pyyaml rasterio fiona 

# install jupyter notebook and matplotlib (not strictly required but highly recommended for interactive usage)
conda install matplotlib jupyter

# install niche itself
pip install niche_vlaanderen

# activate niche again (makes sure all environment variables are set)
# this command must always be run before starting niche
activate niche

# test
niche --help
```

**Comment by WimMertens** [comment]
This is what I get after "niche --help"


![Knipsel](https://user-images.githubusercontent.com/41145810/60335071-42bb5800-999d-11e9-917f-ea7f233e48d3.PNG)

Is that a successfull test?

**Comment by johanvdw** [comment]
That doesn't look good :\
can you try
```
conda install gdal
```
and activate again?

**Comment by WimMertens** [comment]
I had to restart anaconda and did the following:
activate niche
conda install gdal
activate niche
niche --help

Same result

**Comment by johanvdw** [comment]
Can you send me the output of  `conda list -n niche` ?

**Comment by WimMertens** [comment]
(niche) C:\Users\wim_mertens>list -n niche
'list' is not recognized as an internal or external command,
operable program or batch file.


*Wim Mertens*Monitoringsverantwoordelijke Sigmaplan

Vlaamse Overheid
AGENTSCHAP *NATUUR & BOS*

p/a INSTITUUT voor *NATUUR- *en
*BOSONDERZOEK*Herman Teirlinckgebouw, Site Thurn & Taxis
Havenlaan 88 bus73, 1000 Brussel

*T*  0499 58 99 16
*E *wim.mertens@INBO.be <wim.mertens@lne.vlaanderen.be>

*www.natuurenbos.be* <http://www.natuurenbos.be/>    *www.sigmaplan.be
<http://www.sigmaplan.be/>*

De inhoud van dit bericht en eventuele bijlage(n) verbinden het Agentschap
voor Natuur en Bos niet, zolang niet bevestigd door een geldig ondertekend
document.


Op vr 28 jun. 2019 om 14:08 schreef Johan Van de Wauw <
notifications@github.com>:

**Comment by johanvdw** [comment]
you must add conda in the command
(niche) C:\Users\wim_mertens>conda list -n niche

**Comment by WimMertens** [comment]
ok sorry,
with cona I get this (it is long):

# packages in environment at
C:\Users\wim_mertens\AppData\Local\Continuum\miniconda3\envs\niche:
#
# Name                    Version                   Build  Channel
affine                    2.2.2                    py37_0
attrs                     19.1.0                   py37_1
backcall                  0.1.0                    py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2019.5.15                     0
certifi                   2019.6.16                py37_0
click                     7.0                      py37_0
click-plugins             1.1.1                      py_0
cligj                     0.5.0                    py37_0
colorama                  0.4.1                    py37_0
curl                      7.64.1               h2a8f88b_0
cycler                    0.10.0                   py37_0
decorator                 4.4.0                    py37_1
defusedxml                0.6.0                      py_0
entrypoints               0.3                      py37_0
expat                     2.2.5                he025d50_0
fiona                     1.8.4            py37h22081e2_0
freetype                  2.9.1                ha9979f8_1
freexl                    1.0.5                hfa6e2cd_0
gdal                      2.3.3            py37hdf43c64_0
geos                      3.7.1                h33f27b4_0
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.4               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
intel-openmp              2019.4                      245
ipykernel                 5.1.1            py37h39e3cac_0
ipython                   7.5.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.4.2                    py37_0
jedi                      0.13.3                   py37_0
jinja2                    2.10.1                   py37_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.0.1                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.2.4                    py37_0
jupyter_console           6.0.0                    py37_0
jupyter_core              4.4.0                    py37_0
kealib                    1.4.7                h07cbb95_6
kiwisolver                1.1.0            py37ha925a31_0
krb5                      1.16.1               hc04afaa_7
libboost                  1.67.0               hd9e427e_4
libcurl                   7.64.1               h2a8f88b_0
libgdal                   2.3.3                h10f50ba_0
libiconv                  1.15                 h1df5818_7
libkml                    1.3.0                he5f2a48_4
libnetcdf                 4.6.1                h411e497_2
libpng                    1.6.37               h2a8f88b_0
libpq                     11.2                 h3235a2c_0
libsodium                 1.0.16               h9d3ae62_0
libspatialite             4.3.0a              hc36aec2_19
libssh2                   1.8.2                h7a1dbc1_0
libtiff                   4.0.10            h2929a5b_1001
libxml2                   2.9.9                h464c3ec_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py37he774522_0
matplotlib                3.1.0            py37hc8f65d3_0
mistune                   0.8.4            py37he774522_0
mkl                       2019.4                      245
mkl_fft                   1.0.12           py37h14836fe_0
mkl_random                1.0.2            py37h343c172_0
msys2-conda-epoch         20160418                      1
munch                     2.3.2                    py37_0
nbconvert                 5.5.0                      py_0
nbformat                  4.4.0                    py37_0
niche-vlaanderen          1.0                      pypi_0    pypi
notebook                  5.7.8                    py37_0
numpy                     1.16.4           py37h19fb1c0_0
numpy-base                1.16.4           py37hc3f5095_0
openssl                   1.1.1c               he774522_1
pandas                    0.24.2           py37ha925a31_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
parso                     0.4.0                      py_0
pcre                      8.43                 ha925a31_0
pickleshare               0.7.5                    py37_0
pip                       19.1.1                   py37_0
proj4                     5.2.0                ha925a31_1
prometheus_client         0.6.0                    py37_0
prompt_toolkit            2.0.9                    py37_0
pygments                  2.4.2                      py_0
pyparsing                 2.4.0                      py_0
pyqt                      5.9.2            py37h6538335_2
pyrsistent                0.14.11          py37he774522_0
python                    3.7.3                h8c8aaf0_1
python-dateutil           2.8.0                    py37_0
pytz                      2019.1                     py_0
pywinpty                  0.5.5                 py37_1000
pyyaml                    5.1              py37he774522_0
pyzmq                     18.0.0           py37ha925a31_0
qt                        5.9.7            vc14h73c81de_0
qtconsole                 4.5.1                      py_0
rasterio                  1.0.21           py37h6bd7d87_0
rasterstats               0.13.1                   pypi_0    pypi
send2trash                1.5.0                    py37_0
setuptools                41.0.1                   py37_0
shapely                   1.6.4            py37h222a598_0
simplejson                3.16.0                   pypi_0    pypi
sip                       4.19.8           py37h6538335_0
six                       1.12.0                   py37_0
snuggs                    1.4.6                      py_0
sqlite                    3.28.0               he774522_0
terminado                 0.8.2                    py37_0
testpath                  0.4.2                    py37_0
tk                        8.6.8                hfa6e2cd_0
tornado                   6.0.2            py37he774522_0
traitlets                 4.3.2                    py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
wheel                     0.33.4                   py37_0
widgetsnbextension        3.4.2                    py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
xerces-c                  3.2.2                ha925a31_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
zeromq                    4.3.1                h33f27b4_3
zlib                      1.2.11               h62dcd97_3


*Wim Mertens*Monitoringsverantwoordelijke Sigmaplan

Vlaamse Overheid
AGENTSCHAP *NATUUR & BOS*

p/a INSTITUUT voor *NATUUR- *en
*BOSONDERZOEK*Herman Teirlinckgebouw, Site Thurn & Taxis
Havenlaan 88 bus73, 1000 Brussel

*T*  0499 58 99 16
*E *wim.mertens@INBO.be <wim.mertens@lne.vlaanderen.be>

*www.natuurenbos.be* <http://www.natuurenbos.be/>    *www.sigmaplan.be
<http://www.sigmaplan.be/>*

De inhoud van dit bericht en eventuele bijlage(n) verbinden het Agentschap
voor Natuur en Bos niet, zolang niet bevestigd door een geldig ondertekend
document.


Op vr 28 jun. 2019 om 15:44 schreef Johan Van de Wauw <
notifications@github.com>:

**Comment by WimMertens** [comment]
any news on this issue?


*Wim Mertens*Monitoringsverantwoordelijke Sigmaplan

Vlaamse Overheid
AGENTSCHAP *NATUUR & BOS*

p/a INSTITUUT voor *NATUUR- *en
*BOSONDERZOEK*Herman Teirlinckgebouw, Site Thurn & Taxis
Havenlaan 88 bus73, 1000 Brussel

*T*  0499 58 99 16
*E *wim.mertens@INBO.be <wim.mertens@lne.vlaanderen.be>

*www.natuurenbos.be* <http://www.natuurenbos.be/>    *www.sigmaplan.be
<http://www.sigmaplan.be/>*

De inhoud van dit bericht en eventuele bijlage(n) verbinden het Agentschap
voor Natuur en Bos niet, zolang niet bevestigd door een geldig ondertekend
document.


Op vr 28 jun. 2019 om 15:44 schreef Johan Van de Wauw <
notifications@github.com>:

**Comment by johanvdw** [comment]
Wim,

Eerst en voorla mijn excuses voor de enorme vertraging. Ik ben begin juli op verlof vertrokken en was dit dan uit het oog verloren.

Ik stel voor dat je het volgende probeert:
`conda remove --name niche --all`
Het doel hier is om de vorige installatie ongedaan te maken.

`conda create --name niche --file niche_vlaanderen_conda.txt`
Dit maakt een installatie die identiek is aan degene die ik net getest heb. Het bestand niche_vlaanderen_conda.txt zit in bijlage bij dit bericht.

en tenslotte:
```
activate niche
pip install niche_vlaanderen
```
[niche_vlaanderen_conda.txt](https://github.com/inbo/niche_vlaanderen/files/3534651/niche_vlaanderen_conda.txt)

Indien dit niet lukt stel ik voor om eens samen te zitten.

**Comment by johanvdw** [comment]
De installatieinstructies zijn aangepast.
