### ISSUE TITLE
Zonal_stats: use your own ID field instead of default shape_id

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#261]
* niche_vlaanderen version: enhancement for > version 1.1
* Python version: 3

## Niche Python Package 

It would be practical to be able to use my own existing ID field as identifier for the shapes instead of the default shape_id.

Could the zonal_stats function be adapted to use the own ID field if specified?  The name of the ID field would be a new parameter, if this parameter is left empty, zonal_stats would use the shape_id.
We could require the custom id field type to be e.g. a positive integer (-1 could then still be used as code for zones outside the shapes , as it is the case now with shape_id = -1)

**Comment by johanvdw** [comment]
@cecileherr , you can already add a custom attribute, I think you can just add your own ID field in there. 
https://inbo.github.io/niche_vlaanderen/lowlevel.html#niche_vlaanderen.Niche.zonal_stats

**Comment by cecileherr** [comment]
Ahum, thanks Johan! Probably we were not well awake when we decided to post this issue :-) I mark it as solved
