### ISSUE TITLE
Output NicheDelta: optional category refinement

### ISSUE THREAD

**Issue by DriesAdriaens** [inbo/niche_vlaanderen#264]
* niche_vlaanderen version: >1.1
* Python version: 3
* Operating System: Win

## Niche Python Package feature request: optionally split current categories of NicheDelta output

Building further on the request to split the current category "not present" of the Niche output into more detail (soil type not suitable or -additionally- groundwater regime/other factors not suitable; [issue 263](https://github.com/inbo/niche_vlaanderen/issues/263)) this request can be extended to the outcome of model comparison as done by [NicheDelta](https://inbo.github.io/niche_vlaanderen/lowlevel.html#niche-delta). When comparing two NICHE models, the current legend
- 0: “not present in both models”
- 1: “present in both models”
- 2: “only in model 1”
- 3: “only in model 2”
- 4: “nodata in one model”

could then be further split up (possible new values between brackets)
> 0 into
> - ST1 + ST2 (soil types (*ST*) in both model 1 and 2 unsuitable) [1]
> - ST1 + GW2/OT2 (*ST* in model 1 unsuitable, and groundwater regime (*GW*) or other factors (*OT*) unsuitable in model 2) [2]
> - GW1/OT1 + ST2 [3]
> - GW1/OT1 + GW2/OT2 [4]

> 1 not to be split up [9]

> 2 into
> - OK1 + ST2 [5]
> - OK1 + GW2/OT2 [6]

> 3 into
> - ST1 + OK2 [7]
> - GW1/OT1 + OK2 [8]

> 4 not to be split up [0]

knowing that in NICHE the soil type (*ST*) is an a priori condition that has to be met before groundwater regime (*GW*; for "simple" model with ``full_model = true``) or other factors (*OT*; for "full" model with ``full_model = true``) are assessed as further limiting a vegetation's potential occurrence in either of both models to be compared (*1/2*). So, *GW/OT* unsuitable always implicitely means that soil type is already suitable at a given location.

Splitting up the current legend could be made optional via an extra parameter (e.g. ``legend = extended``) in the ``plot`` and ``write`` statements, as suggested in [issue 263](https://github.com/inbo/niche_vlaanderen/issues/263) too.

**Comment by cecileherr** [comment]
I will close this issue because it is more complex than it seems (could lead to too many categories). We will reopen it if we can think of a good approach to do this
