### ISSUE TITLE
Documentation website is offline (since 10/1/2022?)

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#279]
The website with the [documentation](https://inbo.github.io/niche_vlaanderen/) has been returning a 404 error since monday 10-Jan-2022.

Is this intended (if yes, could you please let me know so that I can inform the consultant who noticed it that the site is under maintenance)? Or could you please check what the problem is?

Many thanks in advance!

**Comment by johanvdw** [comment]
It went offline yesterday. I'm working on a fix.

**Comment by johanvdw** [comment]
The documentation is back.
