### ISSUE TITLE
Use (text) soil codes instead of numeric codes in code tables

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#28]

**Comment by johanvdw** [comment]
New soil codes provided by @cecileherr 
[Soil_NICHE.txt](https://github.com/inbo/niche_vlaanderen/files/1406503/Soil_NICHE.txt)

**Comment by johanvdw** [comment]
We should not use different short_names for the same soil_code. As the data will be a grid file containing only numeric values, we don't know which one (open water, ...) the value of 100000 is.
I suggest using one row: 100000 with description 'no soil: open water, ....'.

**Comment by johanvdw** [comment]
For the numeric codes: I would no longer multiply by 10000 by default: eg new grids should use values: 2,3,5,...11
We can still support grids using the old convention (to rerun old projects, for compatibility with tools). In that case we divide by 10000 (exactly) when importing.

**Comment by johanvdw** [comment]
@cecileherr: 40000,KX,keileem,3 is missing in the new table - is this correct?

**Comment by cecileherr** [comment]
Yes, correct, KX is not used in this version (type not relevant for Flanders)

**Comment by johanvdw** [comment]
Ok, Should we remove corresponding values from all code tables?
Eg:
https://github.com/inbo/niche_vlaanderen/blob/master/system_tables/nitrogen_mineralisation.csv#L40

**Comment by johanvdw** [comment]
Performance has degraded with this update. It is probably better to use the numeric code internally, but expose the text code to the users.
