### ISSUE TITLE
Language rules for this repo

### ISSUE THREAD

**Issue by peterdesmet** [inbo/niche_vlaanderen#3]
1. Follow [pep8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) for naming package, variables, etc.
2. Use English for **everything**, including directory names, file names, variable names, comments, column headers, READMEs, issues, etc. Please ask for exceptions and translation of certain jargon.
3. Use `.csv` for tabular data (not `.txt`)
4. Use **either** `.rst` (Sphinx) or `.md` (MKdocs) for all documentation (don't mix).

**Comment by johanvdw** [comment]
@peterdesmet , thanks for the feedback
just a quick note: I'm planning to rename the txt files while I review them (to capture their history). 

For the usage of English: should we also use this for user facing documentation? This is important as this is what I'm working on first, before adding tests and code.

**Comment by peterdesmet** [comment]
@johanvdw I would say yes, also for user facing documentation, but let me consult with Stijn.

**Comment by stijnvanhoey** [comment]
(Adding excerpt from e-mail Cécile here)

> Voor de taal van de (niet technische) handleiding/documentatie en voor de interface voor de gebruiker zouden we toch opteren voor het NL. 
Voor de code zelf en de technische documentatie laat ik de keuze aan jullie (misschien eerder EN als jullie de code door externen via GitHub  willen laten becommentariëren?)

So, technical documentation, code, any development discussion can be in english. I would propose to have a more non-technical documentation in both languages. With respect to `voor de interface`, I would take this out of scope for the initial Python package implementation and consider dutch support on any kind of GUI-app that would be wrapped around the package.

**Comment by johanvdw** [comment]
Note I've made all current documentation still in Dutch. I could copy parts of the original documentation and use original terminology. Only when we settle on the right words for every step (it still is a bit of a mess right now) I think it makes sense to translate them.

**Comment by johanvdw** [comment]
Background documentation about the inners of the model will remain in Dutch. New documentation concerning the usage of the module will be in English.
