### ISSUE TITLE
Calibration module: make HAB-pHAB fields case insensitive

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#302]
* niche_vlaanderen version: dev 1.1
* Python version: 3
* Operating System: Win

Would it be possible to make the script insensitive for the letter case of the fields HAB0/hab0 and pHAB0/PHAB0/phab0?
I realize that the case may differ between different versions of the habitatmap., so it would come in handy.

**Comment by johanvdw** [comment]
fixed also for proportion
