### ISSUE TITLE
Aanmaak/Verspreiding NICHE bodemkaart

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#31]
Uit mail Cécile:

> Weet je al hoe de standaard inputlagen van NICHE (bv. een bodemkaart ...) ter beschikking van de gebruikers zullen/kunnen worden gesteld?
> 
> Ik stel de vraag omdat de NICHE bodemkaart momenteel ook in andere projecten gebruikt wordt: het Agentschap voor Natuur-en Bos zou dus graag een stabiele link met de laatste versie van de kaart ter beschikking willen hebben. 
> Komt er zoiets in kader van het MMIS project? (momenteel heb ik gewoon een link naar een Google Drive, niet echt optimaal dus)

**Comment by stijnvanhoey** [comment]
Next steps:

* [ ] @johanvdw checks with VPO/DOV about the combined classes in certain table columns which would improve the current analysis of Cécile
* [ ] we will implement the conversion from soil map to niche soil map as module in the package. 
* [ ] the publication of the niche soil map as an individual map will be checked with the GIS team

**Comment by johanvdw** [comment]
There is a conversion table for the unisoiltypes.
I've attached it. Before using check that every type that is used is filled. I filled the texture values already for a different project. Drainage and profile development are incomplete.

If we make changes to this file, it should flow back to VPO.
[lnkunitype_zeepolders.txt](https://github.com/inbo/niche_vlaanderen/files/1506607/lnkunitype_zeepolders.txt)

**Comment by johanvdw** [comment]
Not a priority now.
