### ISSUE TITLE
Separate release: change sign groundwater levels

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#319]
niche_vlaanderen uses negative values for groundwater levels above ground level and positive values for groundwater levels below ground, as in [niche_vegetation.csv](https://github.com/inbo/niche_vlaanderen/blob/master/niche_vlaanderen/system_tables/niche_vegetation.csv)

Unfortunately the inbo database with all the groundwater levels (Watina) uses the opposite rule.
We would like to release a new niche_vlaanderen version according to the sign convention used in Watina (that is: negative values for groundwater levels below ground)

It implies at least changing the signs in:

- [niche_vegetation.csv](https://github.com/inbo/niche_vlaanderen/blob/master/niche_vlaanderen/system_tables/niche_vegetation.csv)
- [soil_mlw_class.csv](https://github.com/inbo/niche_vlaanderen/blob/master/niche_vlaanderen/system_tables/soil_mlw_class.csv)
- ...

and controlling the rest of the code and tables.

We should probably add a check to give a warning if we suspect the wrong sign gets used (e.g. based on the fact that we expect larger absolute values below ground than above ground -in most cases  ?)

**Comment by geohydrodata** [comment]
Hello @cecileherr,

Does the ["seepage" parameter](https://inbo.github.io/niche_vlaanderen/invoer.html#seepage) also have to change sign/direction? What does Watina assume for this parameter?

**Comment by stijnvanhoey** [comment]
> @stijnvanhoey Bij test_validation.py: Op
> 
> https://github.com/inbo/niche_vlaanderen/blob/d9a41fcb4bde86944963d4a053748c6e2234a9a1/niche_vlaanderen/validation.py#L126
> 
> wordt een error gegeven omwille van type conflict tijdens pd.merge bij de 'HAB4' column. Andere 'HAB' kolommen passeren. Mogelijk upstream probleem met data, of met pandas versie verandering?

As discussed and patched in the meanwhile, this is now fixed.
