### ISSUE TITLE
Validation: area_pot_perc not yet in % ( <> area_pot_perc_optimistic)

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#327]
* niche_vlaanderen version: master as of 25/1/2023
* Python version: 3
* Operating System: Win

`area_pot_perc `is still a proportion and not a percentage (while `area_pot_perc_optimistic ` is already in %)
=> we should use `area_pot_perc ` = **100***[pot]/ ([pot]+[non_pot]) in %

I post this issue as a reminder - even if we might not need this since we might drop the non optimistic option (= the option that does not take phab into account) -

**Comment by johanvdw** [comment]
Closed in https://github.com/inbo/niche_vlaanderen/commit/0536d4f4f242c31d206d0c5e283b130f3ad814b9
