### ISSUE TITLE
pandas futurewarning

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#354]
/home/runner/work/niche_vlaanderen/niche_vlaanderen/niche_vlaanderen/vegetation.py:218: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.

**Comment by stijnvanhoey** [comment]
closing, fixed by #370
