### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/niche_vlaanderen#36]
The [current documentation structure](https://inbo.github.io/niche_vlaanderen/index.html) is rather unclear for individual users with different needs (applying the model, developer,...).  The main structure is as follows:

* Invoer rasters  *explains the inputs, non-technical, dutch*
* Berekening Trofie (nutrient_level)  *explains the trofie model module, non-technical, dutch*
* Bepaling van de zuurgraadklasse *explains the zuur model module, non-technical, dutch*
* Bepaling vegetatie *explains the vegetation model module, non-technical, dutch*
* Running Niche *provides reference of main Niche() class & 1 example, semi-technical*
* Low level interface  *provides reference of submodules, technical*
* Code Tables  *provides model information, i.e. the classes; non-techhnical*

We should improve the structure, clearly split tech/non-tech and at the same time add some more information for different types of users (someone just interested in model concept, someone to use the model, someone to dev the code). To have this started, just a possible structure for the documentation:

* Main index/introduction (i.e. an extended version of the readme file); add also minimal information on how to apply the model in Python itself or how to run the model from command line with a config file (for the lazy people ;-)
* Niche model concept  (* non-technical, information for people interested in model concept*)
    * Introduction
    * Niche model input rasters, cfr. 'Invoer rasters  *explains the inputs, non-technical, dutch*'
    * Berekening Trofie (nutrient_level)  *explains the trofie model module, non-technical, dutch*
    * Bepaling van de zuurgraadklasse *explains the zuur model module, non-technical, dutch*
    * Bepaling vegetatie *explains the vegetation model module, non-technical, dutch*
    * Niche model outputs (explains the output maps non-technical)
* `niche_vlaanderen` Python Package
    * Tutorials (check if able to do in rendered notebooks)
        * case study, detailed explanation of running the Niche model (loading the inpute, running and checking the outputs
        * case study, comparing 2 scenario's from a single study area and showcasing the features to do scenario comparison
    * Low level interface 
        * Reference of Niche class
        * Reference of the module classes
        * Reference of other implemented

**Comment by peterdesmet** [comment]
Agreed.

1. The main index/introduction should be exactly the same as the README: that way we only have a single intro file to maintain.
2. Niche model concept: all in Dutch
3. Package: all in English
    - First documenting the components of the package (low level interface)
    - Then two tutorials, with input data included

**Comment by stijnvanhoey** [comment]
cfr. #29 , make sure we include a page on the `cli` of niche, I would add this as a separate subsection of the `niche_vlaanderen` Python Package

**Comment by johanvdw** [comment]
I like this proposal as well - thanks for writing it out.

**Comment by stijnvanhoey** [comment]
With respect to the tutorials we will take into account and provide to the user as an example notebook, we should define cases that are ok to put public. @cecileherr  will provide these to @johanvdw.

**Comment by stijnvanhoey** [comment]
With respect to the config file, we should create a separate page in the documentation with different config-file examples, supporting different scenario's (simple model,...) instead of the current loooong config with lots of commands in between.

**Comment by stijnvanhoey** [comment]
@johanvdw  I see that the current documentation of the `Niche python package` is getting of with the specs we discussed here. As new features were added, this is logically. However, we should make sure the documentation keeps clear. I propose the following sections in the documentation of the package:

* niche_vlaanderen Python Package
    * Installation
    * Tutorials:  *each bullet is a separate notebook*
        * Getting started: the simplified Niche model *link to this one in the readme; add here also the idea of using `nv`,...*
        * The Niche model workflow *cfr. current demo usage with subtitles/sections on: 1. setting up niche model, 2. get statistics per shape and 3. deviation maps; make sure to improve descriptions/titles/...!*
        * Comparing Niche models: a notebook that takes two models, runs them and compares them
        * Application of the Floodplain module
    * Niche configuration file (make this Using Niche from the command line)
        * How to run a Niche model from the command line?
        * Example configuration files for Niche: *bullets can be sections, not individual pages; I would provide in each section a proper example configuration file*
            * simplified Niche model
            * full Niche model
            * Niche model with floodplains module
        * Extract Niche configuration file from existing model defined in Python
    * Low level interface
        * Niche
        * NutrientLevel
        * Acidity
        * Vegetation
        * NicheDelta
        * FloodPlain

**Comment by stijnvanhoey** [comment]
some comments regarding the config-sections:
- we're missing an example file with floodplain module
- having twice the *full* (once *model* and once *example*) section, the structure is less clear
- link `advanced_usage.ipynb#Using-abiotic-grids.`   not working

**Comment by johanvdw** [comment]
I think that as of [release 1.0a11[(https://github.com/inbo/niche_vlaanderen/releases/tag/1.0a11) most issues have been covered, and the structure is in place. If documentation changes need to occur - I think it is better to make more targeted issues.
