### ISSUE TITLE
Result per zone

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#37]
Split the results per zone, based on a vector input source (eg shapefile).

Split off from #22.

**Comment by stijnvanhoey** [comment]
Hence, after a model run, the input to extract results on polygon basis is a shapefile with N polygons. For each polygon, the surface area for each vegatation type for each polygon is reported in a table. 
No data values surface area is reported as well, just as the other types.

**Comment by johanvdw** [comment]
Closed in cfcd97d9e558f1be85465639cb49f4832f117242
