### ISSUE TITLE
Gui for model configuration

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#38]
Splitting of the discussion at #29:

> It would be OK (or even easier) for us to use a text file, but I think we should still have some kind of GUI / front end for (some) users.
> An unexperienced user must also be able to see what the possible options to run NICHE Vlaanderen are and ideally find some information for each possible choice.

**Comment by stijnvanhoey** [comment]
As decided on November 7th, we will keep development of the GUI currently out of scope and further focus on documentation.

Still, we see following technical options for development that can be explored, when this would be worthwhile:
 - QGIS plugin
 - flask webapp
 - feasible to express this in lambda function?

**Comment by cecileherr** [comment]
I will close this. This is not a prioritary issue at all for the moment.
