### ISSUE TITLE
DeprecationWarning on backend2gui matplotlib when running inside jupyter notebook

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/niche_vlaanderen#380]
As reported by @cecileherr:

There is a new warning when I use mymodel.plot("mhw"):

```
C:\Users\cecile_herr\.conda\envs\niche_dev\Lib\site-packages\IPython\core\pylabtools.py:77: DeprecationWarning: backend2gui is deprecated since IPython 8.24, backends are managed in matplotlib and can be externally registered.
  warnings.warn(
```

**Comment by stijnvanhoey** [comment]
I did a check using the updated versions in https://github.com/inbo/niche_vlaanderen/pull/385 and the warning did no longer appear on the example notebooks of the docs folder.

**Comment by cecileherr** [comment]
With a new installation (py 3.11) based on the new instructions in PR #385: no warning anymore!

**Comment by stijnvanhoey** [comment]
Handled by #385 , closing
