### ISSUE TITLE
Pushing to master/updating gh-pages /...

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#4]
I'm a bit in doubt what is the best strategy to follow for the repository. Should I commit to master immediately or should we always do pull requests. As currently everything is still in flux  
What about documentation updates (github pages). Do we publish only the documentation for released versions (and publish intermediate versions eg to my gh-pages).

**Comment by peterdesmet** [comment]
My 2 cents:

While everything is in flux, it's fine to commit to master directly. Once it's more stable, use features branches and pull requests to master.

Rather than using a `gh-pages` branch, render the site from the `docs` folder, so it's always in sync with master.

**Comment by johanvdw** [comment]
Ok, cool, that was exactly my idea. Once we have unit tests into place I think it makes sense to always have a pull request.

I will investigate how to build the docs.

**Comment by peterdesmet** [comment]
Like this, but I'll let you do it. Please remove `gh-pages` branch afterwards.

<img width="771" alt="screen shot 2017-09-12 at 10 52 56" src="https://user-images.githubusercontent.com/600993/30316786-93d67920-97a8-11e7-9917-482b2ad66d6d.png">

**Comment by johanvdw** [comment]
@peterdesmet 

I tried on my own fork (I don't have access here). But I have the impression that it is not possible to render RST files from the docs dir directly.

**Comment by peterdesmet** [comment]
Just gave you admin rights: can you test if rst work? If not, how would sphinx render the docs?

**Comment by johanvdw** [comment]
What I do now is use `make publish` in the docs dir. This updates the gh-pages dir and pushes it. It relies on https://github.com/davisp/ghp-import , which is packaged in debian.

We can probably run this on travis as well - though we should check if this can be done only on master and not on pull requests.

See eg: https://gist.github.com/brenns10/f48e1021e8befd2221a2
(code can be simplified a lot if using ghp-import.

**Comment by peterdesmet** [comment]
A make file to generate the documentation and push it to gh-pages seems convenient enough.

It would indeed be cool if Travis could run this for any change on master.

**Comment by johanvdw** [comment]
We have a makefile to generate documentation. Automated publishing is a seperate issue:
https://github.com/inbo/niche_vlaanderen/issues/7
