### ISSUE TITLE
Add a name to model options

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#41]
It is probably a good idea to have a 'name' attribute to our models.
This is especially the case when different scenario's are run. We can then add this name to the outputfiles and the logfiles. eg scen1_V11.tif, ...

**Comment by stijnvanhoey** [comment]
As in discussion, the improved option of custom names on the output side, would be a good enhancement.

**Comment by stijnvanhoey** [comment]
The output name options should be available in the cli interface as well as a command line argument
 e.g. `..... -o modelname`

**Comment by johanvdw** [comment]
Ook op plot

**Comment by johanvdw** [comment]
added to plot as of 65dce919447e19961165d618482a2fbe64cb4b90
