### ISSUE TITLE
Too many classes in SoilGLGClass?

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#5]
Table [SoilGLGClass](https://github.com/inbo/niche-vlaanderen/blob/master/SystemTables/SoilGLGClass.csv) contains values for SoilGLGClass from 1 to 9. 

However table [ZuurClass](https://github.com/inbo/niche-vlaanderen/blob/master/SystemTables/ZuurClass.csv) which uses this value always has the same values when using either of (1,4,7), (2,5,8) or (3,6,9). We could therefore simplify this to have only three classes (low, medium, high SoilGLGClass).

**Comment by stijnvanhoey** [comment]
@johanvdw can you double check this with Cécile/Dries?

**Comment by cecileherr** [comment]
I cannot give you a direct answer, I also need to dive back into the decision rules and the reclass tables, but I added this question to my to do list

**Comment by johanvdw** [comment]
This is not a blocking issue - with the current values it does not make sense to duplicate the groups - but we could keep it like this to enable future changes.

It does not matter for the code developed.

**Comment by cecileherr** [comment]
The current pH rule often leads to bad pH predictions for sandy silts in the Kempen area. Using extra soil classes might be one of the possible solutions to solve this problem so I would keep the extra classes for the moment. (Other option: use other rules, i.e. other categories in the reclass tables, for the different biogeographical regions)

**Comment by johanvdw** [comment]
Ok,
I'll leave this.
