### ISSUE TITLE
Pypi registration

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/niche_vlaanderen#50]

**Comment by stijnvanhoey** [comment]
see https://github.com/inbo/niche_vlaanderen/pull/52

**Comment by stijnvanhoey** [comment]
@johanvdw does this work? You can already provide a current version on Pypi and just define the alpha status

**Comment by johanvdw** [comment]
yep, if we agree on a version number for alpha releases
I propose:
1.0a1 ?

**Comment by johanvdw** [comment]
Publishing seems to work
https://pypi.python.org/pypi/niche-vlaanderen

**Comment by johanvdw** [comment]
It would be nice that we check that the git tag matches the version number, but let's close for now.
