### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#53]
What version numbers should we be using?
As this is the second reimplementation of niche_vlaanderen, I would use 2.0.0, but one could argue for 3.0.0 if we include the VBA version.

How should we update version numbers in the future, especially if they are changing the code tables and affecting the model results. Should this be a bump in minor version (as the interface is the same), ...

**Comment by stijnvanhoey** [comment]
Good question! 

I would not take into account the previous versions, as these were never distributed and more a personal-written tool. I would aim for a first release 1.0.0 to define the current Niche model first stable implementation. 

* patches are labelled as patches and we could even argue if we really want to include this (why not just 1.0?)
* code tables are minor changes indeed 
* explicitly new interfaces/model developments would result in major and release (and archiving on Zenodo)

**Comment by johanvdw** [comment]
Sticking to 1.0axxx for the alpha releases (testing whether the deploy on pypi works etc). 
I will use 1.0bx for the first beta release, which I hope will be close to a release candidate for 1.0 by the end of the month.
