### ISSUE TITLE
Current namespace is ambigious

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/niche_vlaanderen#55]
The current namespace that is available to the user provides the following methods/attributes:

```
'Acidity',
'Niche',
'NutrientLevel',
'Vegetation',
'acidity',
'codetables',
'niche',
'nutrient_level',
'spatial_context',
'vegetation',
'version'
```

Hence, `acidity`/`Acidity`, `niche`/`Niche`,... This creates confusion to the user

**Comment by johanvdw** [comment]
@stijnvanhoey Any suggestions how to solve this?

**Comment by stijnvanhoey** [comment]
An option for the `Acidity` and `NutrientLevel` is to not include them in the `__init__` , as these are then still loadable, but not visual (at least, that is what I assume). 

With respect to the `niche`, I just would like to have only the class `Niche` available to the user and not the module `niche`. I do think it can be achieved by adapting the `__init__` file, but we will have to experiment a bit to get the proper behaviour (start with an empty `__init__` and see how it behaves).
