### ISSUE TITLE
Failed loading ESRI grid

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#56]
* niche_vlaanderen version: 0.0.1
* Python version: 3.6  (this is not mentioned in the log!)
* Operating System: windows 7

## Niche Python Package question
(please add the label `niche_package` at the right hand side) -> I can't!

### Description

Loading ESRI binary grid (local version on Cécile's computer => ./TD_Grobbendonk/ingrids/bodemveen) provides following error:

```
ERROR:rasterio._gdal:CPLE_OpenFailed in b'Unable to open EPSG support file gcs.csv.\nTry setting the GDAL_DATA environment variable to point to the\ndirectory containing EPSG csv files.'
```
Not all ESRI binary grids give the same error. eg myniche.set_input("mhw","TD_Grobbendonk/ingrids/ghg_mv_model/") is ok

Here is the folder with the problematic ESRI raster:
[bodemveen.zip](https://github.com/inbo/niche_vlaanderen/files/1478849/bodemveen.zip)

**Comment by DriesAdriaens** [comment]
I experienced the same issue, with following error for all Arc/Info Binary Grid (.adf) files (no matter of selecting file itself or its containing folder):
ERROR:rasterio._gdal:CPLE_OpenFailed in b'Unable to open EPSG support file gcs.csv.\nTry setting the GDAL_DATA environment variable to point to the\ndirectory containing EPSG csv files.'

Model can however be runned with seemingly valid rasters ...

**Comment by stijnvanhoey** [comment]
Apparently, this is an Anaconda issue on windows: https://github.com/ContinuumIO/anaconda-issues/issues/2167

Seems to be the unexistence of the environmental variable `GDAL_DATA

**Comment by johanvdw** [comment]
Seems to be fixed in gdal=2.1.3_py36_vc14_7

**Comment by johanvdw** [comment]
There are a few reasons why ESRI grids can fail. One I have seen different time is when a sta.adf (statistics) file is missing. In that case the file will not open in QGIS or give an error when you run gdalinfo on the file (note that if you have installed niche, gdalinfo should be available in the same environment).

Resaving the file from ArcGIS should fix this issue.

In general, it is recommended to use geotiff files: these contain all info in the file itself, so you can not loose a part.

**Comment by johanvdw** [comment]
I have now described both problems in https://inbo.github.io/niche_vlaanderen/faq.html#frequently-asked-questions
If the recommended installation is used - the first error should not occur anymore. The second problem (when eg  STA.ADF is missing) can not be solved in niche, this also occurs in eg qgis and gdal
