### ISSUE TITLE
usage of attribute `log` is unclear

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/niche_vlaanderen#59]
The Niche object provides the attribute `log` to the user. However, this is from the `logging.RootLogger` class and not clear how this should be used by the Niche modeller. Either t should provide a way to call the current log (whenever user wants to) or be hidden to the user namespace.

**Comment by johanvdw** [comment]
Should be private.

(goal is to be to reroute the output in case we are in a web application/plugin/...)
