### ISSUE TITLE
package (and repo) name

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#6]
Hyphens are not allowed in package names 

> Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.
[PEP-8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names)

So I suggest making the package niche_vlaanderen. Would it not be better to rename the repo as well?

**Comment by peterdesmet** [comment]
So it's `niche_vlaanderen` or `nichevlaanderen`. Note: packages with hyphens also exist (e.g. https://github.com/BelgianBiodiversityPlatform/python-dwca-reader) which is in line with how we name our repositories. @niconoe, any advice/input?

Once decided, we should indeed rename the repo.

**Comment by niconoe** [comment]
To me, repo name is less important than package name, but it's of course nice to have the same. 

For the package name, I agree with @johanvdw that we should follow PEP-8. Since `Underscores can be used in the module name if it improves readability`, I also vote for niche_vlaanderen.

**Comment by peterdesmet** [comment]
`niche_vlaanderen` it is then. I've updated the repo name.

**Comment by stijnvanhoey** [comment]
As this is agreed on, closing here.
