### ISSUE TITLE
Labelling of issues not allowed to users

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/niche_vlaanderen#60]
This is asked in the current issue template, but not possible for non-collaborators)

**Comment by johanvdw** [comment]
I suggest we remove the question. It is not like we will have that many requests that users have to label themselves.

**Comment by stijnvanhoey** [comment]
@peterdesmet why can not everyone label his/her own issue?

**Comment by peterdesmet** [comment]
Labelling is reserved for maintainers. 🤷‍♂️
