### ISSUE TITLE
plot functions return

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/niche_vlaanderen#68]
When using plot functions, the user should get the `fig, ax` as return; this enables the possibility to do ad-hoc adaptation later on the plot result in function of other projects.

As input argument `ax=None` is provided. If `None`, an `ax`-object is made internally by the function. If `ax` is provided by the user, the plot is created on the provided `ax` and returned.

**Comment by johanvdw** [comment]
I suggest only returning an ax object. If the function is initialized with only an ax object, we can not return a fig object.
Looks like [pandas plot](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.plot.html) is doing the same

**Comment by stijnvanhoey** [comment]
ok!

**Comment by johanvdw** [comment]
I'm wondering if we can not make the behaviour slightly easier for the non power user: 
if that user does not supply an `ax` argument, we could immediately call plt.show().

This is how this is implemented in rasterio: https://github.com/mapbox/rasterio/blob/master/rasterio/plot.py#L121

**Comment by stijnvanhoey** [comment]
Make sure the experience/workflow for the user, working in a notebook or rather in an IDE is clear.
