### ISSUE TITLE
Statistics per shape representation

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/niche_vlaanderen#70]
When providing a shapefile to calculate the summary statistics, an argument `id_colomn=None` is provided. When provided, this column is used as identifier in the resulting reporting table. The shape identifier is always provided as well. We opt for long format table, as this provides the easiest solution for later 

The resulting table could look as follows:
```
shape_id    ID_KOLOM    vegetatietype   presence    area_m2
1                 ...                      present     30000
2                 ...                      absent      150000  
3                 ...                      no_data     2444
...
```
(with `ID_KOLOM` the name of the user provided column name)

**Remark:** The `.table` method should be consistent with this behavior and provide a long table format as well. In order to support the user in handling this table, provide an example to convert it to short format with [pandas `pivo_table`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.pivot.html#pandas.DataFrame.pivot) in the [documentaton](https://inbo.github.io/niche_vlaanderen/demo.html).

**Comment by johanvdw** [comment]
closed as of bc85640c102bcb83511961e5b9568a7bfb4ad117 and 6ef39c25ae13c0f39a80a1ab0ee7b2613c95fa02
