### ISSUE TITLE
dependency not explicitly mentioned

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/niche_vlaanderen#72]
`rasterstats` not mentioned in the requirements file

**Comment by johanvdw** [comment]
It actually is - but pip does not pick up new requirements by default.

**Comment by johanvdw** [comment]
In this particular case you should use `pip install --ignore-installed`
Or 
`pip install --ignore-installed --upgrade --no-deps --force-reinstall `

to catch all strange pip issues as it is not really build to upgrade.
