### ISSUE TITLE
Check the availability of the example data sets for users after installation

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/niche_vlaanderen#73]
When people want to start using Niche, the availability of the example data sets to the users is essential to get them quickly started. These data sets should not be included somewhere hidden where `pip` puts them, but on any location the user want to work. 

@johanvdw, make sure this is possible. Options are: (1) providing a specific download of the example data using a link; (2) making sure the data can be accessed, independent from installation location,... (3) ...

**Comment by stijnvanhoey** [comment]
I would improve the current description as follows:
- Provide not just the link to the source:
    - explain shortly that thet should download the most recent `zip` on the releases page
    - make sure people are linked to (have knowlegde of)the correct files inside the docs-folder: `getting_started.ipynb`, `floodplain.ipynb` and `advanced_usage.ipynb`. 
    - make sure people do understand the data sets are in the `testcase` folder, from which it can be retrieved as well

**Comment by johanvdw** [comment]
I believe all comments are covered in the current version.
