### ISSUE TITLE
environment file conda to support handling

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/niche_vlaanderen#78]
Also adapt the docuementation: provide some alternative options to fall back on.

**Comment by johanvdw** [comment]
This gave some other issues - currently the method that worked best is the old install, but forcing the correct niche version, eg pip install niche_vlaanderen==1.0a8

**Comment by johanvdw** [comment]
An environment file is now provided. 

Manual installation without an environment is still possible:
```
conda install pandas rasterio rasterstats
pip install niche_vlaanderen==1.0a10
```

in case the environment does not work.
