### ISSUE TITLE
Names for vegetation types are incomplete

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#79]
see eg vegetation type 11.

**Comment by johanvdw** [comment]
This seems to be the case also in the original.

@cecileherr: can you have a look?

**Comment by cecileherr** [comment]
Sorry for the lack of reaction, I thought it was rather a layout problem in the figures
I proposed these changes (see pull request)
veg 10 = RG Phalaris arundinacea-[Convolvulo-Filipendulion]
veg 11 = RG Juncus effusus-[Molinietalia/Lolio-Potentillion]
veg 13 = RG Glyceria maxima [Phragmitatea]
Also removed the spaces around the hyphen in veg 9 Galio-Alliarion, veg 17 Junco-Molinion, veg 24 Oxycocco-Ericion, veg 28 Calluno-Genistion pilosae
