### ISSUE TITLE
Nutrient level: Discrepancy between original documentation and implementation

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#8]
There is some discrepancy between the documentation and the ArcGIS implementation
the arcgis implementation only adds inundation if values for nutrion_level are 3 or lower
he documentation says: 

> Wanneer het hydrologisch model toevoer van gebiedsvreemd water berekent naar een
> gebied waar nog geen waterinlaat plaatsvindt, dan wordt in NICHE aangenomen dat de
> voedselrijkdom daardoor met 1 trofieklasse (extra) toeneemt. (pg 15)

Which would imply that also values of 4 should raise to 5.

The old version is currently implemented (to allow comparison) - but this should be validated.

**Comment by cecileherr** [comment]
Topic added to my to do list

**Comment by cecileherr** [comment]
Documentation p15 refers to the Dutch version of the model => keep the current ArcGIS implementation and only add 1 unit if values for nutrition are 3 or < 3 (Unfortunately I cannot find any explicite documentation for this rule for the Flemish version NICHE Vlaanderen)
