### ISSUE TITLE
Floodplains: handling NoData and zones without flood 

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#87]
Currently all pixels with nodata appear as "niet combineerbaar" / not tolerant to flood (for the simple floodplain models FloodPlain() as well as for the combination Niche - Floodplain). If there is any layer with no data for a given cell (it will mostly be in the Niche part), the output should be a NoData cell and should be labelled as such.

We also would like to add a few new categories to the system tables  to allow us to make a difference between cells with missing data and cells without flooding:
=>  depths.csv: code = 0 and depth = 0 cm
=> lnk_potential.csv: (any combination) depth = 0, potential = 4
=> potential.csv: code = 4 and description = "geen informatie of geen overstroming" (this description might still be adapted in the future)

**Comment by johanvdw** [comment]
I would change the last definition to "no flooding" - as no information is already handled as no data. 

See eg:

![image](https://user-images.githubusercontent.com/868434/36425978-f1d8a7cc-1648-11e8-90b2-5c68efbd60b7.png)

**Comment by cecileherr** [comment]
I understand that a category named "no flooding or no info" might sound strange, but there is a reason for this odd name.
We regularly use GIS layers that are a combination of the results of several surface water models, but not every watercourse has been modelled (yet) and the combined layer does not show the boundaries of the submodels. A blank pixel could therefore be a pixel without flooding ... but also a pixel in an area that has not been modelled yet.

**Comment by johanvdw** [comment]
Rather than adding all possible options to lnk_potential, I have made class 4 the default class, which is overwritten by nodata and any other value which corresponds to the table.

That way, we don't have to add a large number of records to the lnk_potential table.
