### ISSUE TITLE
Seepage: discrepancy between code and documentation

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#9]
The original FluxClass.txt file has these values:
`-999 -1:30

-1 -0.1:20

-0.1 999:10`

This is different from the documentation which says (chapter 2, page 9)

> kwel > 0.1 mm/dag		kwel
kwel –0.1 - 0.1 mm/dag		stagnatie
kwel < -0.1 mm/dag		infiltratie

The lower border for infiltration is -1 in the table and -0.1 in the documentation

**Comment by johanvdw** [comment]
Actually the documentation itself is confusing:

If seepage occur, we want negative values <-0.1 mm . Infiltration occurs if our input grid contains values > 0.1.

**Comment by cecileherr** [comment]
Chapter 2 p 9 of the documentation refers to the original Dutch version of NICHE
> kwel > 0.1 mm/dag	kwel
> kwel –0.1 - 0.1 mm/dag	stagnatie
> kwel < -0.1 mm/dag	infiltratie
BUT this rule still appears in a document from 2007 describing the input layers for NICHE Vlaanderen! 

Table 5.2 (chapter 5 p93) gives the new rule for NICHE Vlaanderen and seems more in accordance with the rules in FluxClass.txt (the use of the < and > signs in this table is quite confusing)

**Comment by cecileherr** [comment]
Also note: the documentation of the current project still reflects the Dutch version (https://inbo.github.io/niche_vlaanderen/invoer.html#overstroming-trofie) and should be adapted in accordance with table 5.2 (p93) of the NICHE report
