### ISSUE TITLE
development documentation

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/niche_vlaanderen#90]
Currently, we have some development documentation about [contribution](https://inbo.github.io/niche_vlaanderen/contributing.html#get-started), but we should as well provide information about the development process:
- the version tag definition (minor/major release,...)
- what does one have to do locally (sphinx,...) and what happens on the CI?

This can be short and technical, but need to be part of the sphinx documentation.

**Comment by johanvdw** [comment]
Added https://inbo.github.io/niche_vlaanderen/contributing.html#version-numbering-scheme
