### ISSUE TITLE
Error in getting started manual with jupiter notebook

### ISSUE THREAD

**Issue by milotictanja** [inbo/niche_vlaanderen#92]
* niche_vlaanderen version:1.0a10
* Python version:3.6
* Operating System:windows7

### Description

I tried to go through the getting started manual, but I got stuck in the first line of code.
I downloaded the niche source code and opened the getting started manual in jupyter notebook (in which I tried to run the code).

### What I Did

```
import niche as nv
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-eb9dae3d6d6d> in <module>()
----> 1 import niche_env as nv

ModuleNotFoundError: No module named 'niche_env'

**Comment by johanvdw** [comment]
Thanks for testing!

I suppose you have used the niche environment installation method. 

Can you verify the installation was succesful by running (from the anaconda prompt):
```
activate niche_vlaanderen
niche --help
```

If that works, can you try starting the jupyter notebook from the same prompt, with the environment activated:
`jupyter`

**Comment by johanvdw** [comment]
Rereading your question:
you should do:
`import niche_vlaanderen as nv`

**Comment by milotictanja** [comment]
solved! Thanks
