### ISSUE TITLE
Error creating conda environment on ubuntu 16.04

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/niche_vlaanderen#94]
When following the instructions to create the conda environment for linux, following error occurred:

```
> conda env create -f ./docs/niche_env.yml 
Fetching package metadata ...........

ResolvePackageNotFound: 
  - boost 1.66.0 py36_vc14_1
```

**Comment by johanvdw** [comment]
Stijn,

You are following the windows instructions. 
https://inbo.github.io/niche_vlaanderen/installation.html#alternative-installation
should work on linux.
Actually you should also be able to install most of the dependencies of niche_vlaanderen using apt, which is how I test this on travis (and locally).

Kind Regards,
Johan

**Comment by stijnvanhoey** [comment]
Great! Worked Fine. Maybe just one remark, provide the information as a new environment as well:
```
conda create -n niche python=3.6 pandas pyyaml rasterio rasterstats matplotlib
pip install niche_vlaanderen
```

Is there any specific reason to specifify the version here? `pip install niche_vlaanderen==1.0a11`? what is we provide a new release?

**Comment by johanvdw** [comment]
The reason I specified a version: if you have an old version in your cache, the latest version will not be installed. The other option would be using --no-cache-dir
https://pip.pypa.io/en/stable/reference/pip_install/#caching
