### ISSUE TITLE
shipping config files with the source code

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/niche_vlaanderen#95]
When working on this section, how do users are able to find out where to get these config-files from? 
![image](https://user-images.githubusercontent.com/754862/36739818-303e2616-1be1-11e8-8760-6e3d87e47d8c.png)

Proposal: provide these config files inside the docs as well and provide a link to the raw data file download or to the relative path in docs (as with the example data).

**Comment by johanvdw** [comment]
These files are actually in the documentation directory
https://github.com/inbo/niche_vlaanderen/tree/master/docs

**Comment by stijnvanhoey** [comment]
OK, than I would inform the user in the docs text that these yaml files can be downloaded/loaded from there. This is not clear at the moment
