### ISSUE TITLE
Niche versions

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#96]
## Niche Python Package question

If I type "niche --version" in the Anaconda prompt I get version 1.0a8, if I first type "activate niche" and then "niche --version", I get 1.0b1. This is quite confusing.

I installed 1.0a11 from the yml file today and then 1.0b1 manually (with pip). I got no error message.

When i try to run a model in Jupyter, it seems it is still version 1.0a8

_Niche Vlaanderen version: 1.0a8
Run at: 2018-02-28 11:20:37.267201_

**Comment by johanvdw** [comment]
@cecileherr 
My error - I forgot to update the yml

**Comment by cecileherr** [comment]
OK, thanks! If I start jupyter from the prompt after having activated niche, I indeed use the new version (and I get errors, more issues to come :-) )

Can I remove the old version that was installed outside the environment anyhow?

**Comment by johanvdw** [comment]
To remove:
`pip uninstall niche_vlaanderen` (outside the environment).

**Comment by cecileherr** [comment]
OK, perfect! Life can be easy :-)

**Comment by johanvdw** [comment]
Closing here: documenting better seems a good idea, but there is an issue for that.
