### ISSUE TITLE
Warning running simple niche model (1.0b1)

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#97]
* niche_vlaanderen version: 1.0b1
* Python version: 3.6
* Operating System: Win

## Niche Python Package question

Using my usual test data for Grobbendonk, I get an error while trying to run the simple niche model (the last line of code triggers the error):

```
import niche_vlaanderen as nv
simple = nv.Niche()
path = "../ingrids/"
simple.set_input("mhw", path + "ghg_mv_model")
simple.set_input("mlw", path + "glg_mv_model")
simple.set_input("soil_code",path + "bodemveen")
simple.run(full_model=False, strict_checks=False)
```

> C:\Users\cecile_herr\AppData\Local\Continuum\anaconda3\envs\niche\lib\site-packages\numpy\core\fromnumeric.py:52: RuntimeWarning: overflow encountered in multiply
>   return getattr(obj, method)(*args, **kwds)
> C:\Users\cecile_herr\AppData\Local\Continuum\anaconda3\envs\niche\lib\site-packages\numpy\core\fromnumeric.py:52: RuntimeWarning: overflow encountered in multiply
>   return getattr(obj, method)(*args, **kwds)

The very same code used to work with version  1.0a08.
Tell me if you need the input data to reproduce this error.

**Comment by johanvdw** [comment]
I can reproduce this. And fixing it should be quite easy.

It is a warning though - I think your model should still have run.

Technical info for myself: error happens when rounding - we should not round if we have integer inputs.
https://github.com/inbo/niche_vlaanderen/blob/master/niche_vlaanderen/niche.py#L354

**Comment by cecileherr** [comment]
Absolutely right, I was too busy writing another issue :-) 
I changed the title
