### ISSUE TITLE
Error running full niche model: nutrient_level categories (1.0b1)

### ISSUE THREAD

**Issue by cecileherr** [inbo/niche_vlaanderen#99]
* niche_vlaanderen version: 1.0b1
* Python version: 3.6
* Operating System: win

## Niche Python Package question
A problem trying to run the full model with the Grobbendonk data set (last line triggers the error):

```
full = nv.Niche()
path = "../ingrids/"
full.set_input("mhw", "C:/Users/cecile_herr/NICHE_LOK/TD_Grobbendonk/ingrids/ghg_mv_model")
full.set_input("mlw", path + "glg_mv_model")
full.set_input("soil_code",path + "bodemveen")
full.set_input("nitrogen_animal", path + "bemest_d")
full.set_input("inundation_acidity", path + "ovstr_z")
full.set_input("inundation_nutrient", path+ "ovstr_z")
full.set_input("nitrogen_fertilizer", path +"bemest_k")
full.set_input("minerality", path + "mineraal01")
full.set_input("management", path + "beheer")
full.set_input("nitrogen_atmospheric", path + "dep1.tif")
full.set_input("msw", path + "gvg_mv_model")
full.set_input("rainwater", path +"nulgrid")
full.set_input("seepage", path + "kwel")
full.run(strict_checks=False)
```

> NicheException                            Traceback (most recent call last)
> <ipython-input-13-d7cc278310da> in <module>()
> ----> 1 full.run(strict_checks=False)
> 
> ~\AppData\Local\Continuum\anaconda3\envs\niche\lib\site-packages\niche_vlaanderen\niche.py in run(self, full_model, deviation, abiotic, strict_checks)
>     533 
>     534         self._vegetation, self.occurrence = vegetation.calculate(
> --> 535             full_model=full_model, **veg_arguments)
>     536 
>     537         if deviation:
> 
> ~\AppData\Local\Continuum\anaconda3\envs\niche\lib\site-packages\niche_vlaanderen\vegetation.py in calculate(self, soil_code, mhw, mlw, nutrient_level, acidity, management, inundation, return_all, full_model)
>     130                              self._ct_acidity["acidity"])
>     131             check_codes_used("nutrient_level", nutrient_level,
> --> 132                              self._ct_nutrient_level["code"])
>     133 
>     134         if inundation is not None:
> 
> ~\AppData\Local\Continuum\anaconda3\envs\niche\lib\site-packages\niche_vlaanderen\codetables.py in check_codes_used(name, used, allowed)
>     168         msg += "used: %s\n" % str(used_codes)
>     169         msg += "possible: %s" % str(allowed_codes)
> --> 170         raise NicheException(msg)
> 
> NicheException: Invalid nutrient_level code used
> used: {0, 1, 2, 3, 4, 5, 255}
> possible: {1, 2, 3, 4, 5, -99, 255}

(And same warning as #97 )

**Comment by johanvdw** [comment]
Thanks for reporting.
![image](https://user-images.githubusercontent.com/868434/36793916-12dc0a5c-1c9f-11e8-82a5-6022d49658d6.png)

**Comment by johanvdw** [comment]
This is actually an interesting find - this error has been present since the start of the project, but was only detected now as I added extra validation on the input files.
It only affected intermediate grids, final grids are unchanged (as a nodata mask was applied there).
